/**
 * Created by Administrator on 2018/12/11.
 */
module.exports={
    entry:'./main.jsx',
    output:{
        filename:'bundle.js'
    },
    module:{
        rules:[
            {
                test:/\.js[x]?$/,
                exclude:/node_modules/,
                use:{
                    loader:'babel-loader',
                    options:{
                        presets:['es2015','react']
                    }
                }
            },
            {
               test:/\.css$/,
                use:[
                    {
                        loader:'style-loader'
                    },
                    {
                        loader:'css-loader',
                        options:{
                            modules:false
                        }
                    }
                ]
            }
        ]
    }
}